[package]
name = "rollable"
version = "0.1.0"
edition = "2021"

[dependencies]
avian3d = "0.2.1"
bevy = "0.15.3"
bevy_hanabi = { version = "0.14", default-features = false, features = [ "3d", "serde" ] }

[profile.dev.package."*"]
opt-level = 3